from . import admin
from . import employee_full
from . import vacation
from . import create_offer
from . import emp_forma
from . import frilans_full
from . import umumiy_oyna
from . import fr_forma
from . import help
from . import start
from . import echo